stages:
  - test
  - mirror
  - deploy

####################
# TEST STAGE
####################
test-job:
  stage: test
  tags:
    - cicd
  script:
    - python3 --version
    - python3 -m ensurepip --default-pip || true
    - python3 -m pip install --upgrade pip
    - python3 -m pip install flask requests
    - python3 -m py_compile log.py
    - echo "Syntax chзeck pashsed"
  only:
    - main
    - merge_requests

####################
# MIRROR TO GITHUB
####################
mirror-to-github:
  stage: mirror
  tags:
    - cicd
  script:
    - git fetch --unshallow || true
    - git remote remove github || true
    - git remote add github https://kiddiv:$GITHUB_TOKEN@github.com/kiddiv/cicd.git
    - git push github HEAD:refs/heads/main --force
  only:
    - main

####################
# DEPLOY STAGE
####################
deploy-job:
  stage: deploy
  tags:
    - cicd
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p $SERVER_PORT $SERVER_IP >> ~/.ssh/known_hosts 2>/dev/null
  script:
    - rsync -avz --delete --exclude='.git/' --exclude='__pycache__/' --exclude='*.pyc' --exclude='.venv/' ./ $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/app/
    - |
      ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP "
        sudo systemctl daemon-reexec &&
        sudo systemctl daemon-reload &&
        sudo systemctl restart logapp &&
        sudo systemctl status logapp --no-pager
      "
  only:
    - main